site_name: Team & Group Training Exercises

nav:
  - Machine Setup:
      - Basics: machine_setup/basics.md
      - Git and Github: machine_setup/git.md
      - Fish: machine_setup/fish.md
  - Linux UM:
      - Shell: linux_um/shell.md
      - Strace: linux_um/strace.md
      - Shtrudel: linux_um/shtrudel.md
      - Tcpdump: linux_um/tcpdump.md

theme:
  name: material
  palette:
    primary: indigo
    accent: pink

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

docs_dir: content
