site_name: Team & Group Training Exercises

nav:
  - Setup:
      - Prerequisites: setup/prerequisites.md
      - Installation: setup/installation.md
  - Linux UM:
      - Introduction: linux_um/introduction.md
      - User Management: linux_um/user_management.md

theme:
  name: material
  palette:
    primary: indigo
    accent: pink

docs_dir: content
